### ISSUE TITLE
Fashion IQ dataset

### ISSUE THREAD

**Issue by GDam90** [BrandonHanx/CompFashion#1]
Hi @BrandonHanx , thanks for this great work! 

However i'm trying to work with this dataset as well, but i cannot retrieve the entire FIQ because many of its links are broken, as reported in many issues in repos that leverages this dataset. How did you adress this problem? Do you have the complete dataset and would you please share it with us in a Drive folder?
By now I've only reduced the dataset by including the only images I was able to get, but clearly i would like to work with the full dataset.

Thank you, hope you can help us on this!

P.S: [here](https://github.com/GDam90/Fashion_IQ_missing_images) I wrote all the missing asin with their broken URLs, I hope it can help.

**Comment by sanLiR** [comment]
> Thank you so much for the quick and effective response, the [link](https://data.nam.ai/fashioniq_images.zip) was just what I was searching for! Many thanks!

Hello, the link here has expired. Do you have a new link address that can be downloaded directly？
