### ISSUE TITLE
about  one image

### ISSUE THREAD

**Issue by Wangld5** [BrandonHanx/CompFashion#2]
Hi
I download the image data you provided, but the image http://ecx.images-amazon.com/images/I/51WUqJu-tKL._SY445_.jpg is lost. Can you provide this image ?

**Comment by BrandonHanx** [comment]
Please refer to https://github.com/hongwang600/fashion-iq-metadata/tree/master/image_url

**Comment by Wangld5** [comment]
I searched the link but found the missing image was not included in the broken image_url

**Comment by BrandonHanx** [comment]
Could you please give me the name of this image?

**Comment by Wangld5** [comment]
It's ok because none of the image_splits uses the image.
