### ISSUE TITLE
About result

### ISSUE THREAD

**Issue by Wangld5** [BrandonHanx/CompFashion#3]
Hi，
Did you get the same result as the paper ？
Thank you for your replay

**Comment by BrandonHanx** [comment]
I got the same with TIRG and RTIC. But not for VAL and CosMo.

**Comment by Wangld5** [comment]
Thank you for your reply. I will try CosMo later

**Comment by BrandonHanx** [comment]
Please reopen this issue or open another one if you have other questions.
