### ISSUE TITLE
14 images are broken

### ISSUE THREAD

**Issue by Wangld5** [BrandonHanx/CompFashion#4]
14 images in dress dataset are broken:
B008583YKC.jpg
B009H3SDPK.jpg
B00A885VUI.jpg
B00AKQBDKU.jpg
B00AZGHX7M.jpg
B00AZJJE1C.jpg
B00AZJJER6.jpg
B00AZJJGDS.jpg
B00AZJJYBM.jpg
B00BTDROGU.jpg
B00BTDS338.jpg
B00C4XCXJM.jpg
B00C621JPK.jpg
B00CM2RZ3E.jpg
Can you find these images ？

**Comment by BrandonHanx** [comment]
As I mentioned for sooooo many times.

Please refer to https://github.com/hongwang600/fashion-iq-metadata/tree/master/image_url/broken_links

**Comment by Wangld5** [comment]
Sorry to waste your time, I solve the problem

**Comment by BrandonHanx** [comment]
Before the next issue, please get as much information as you can from your own side.
I'd like to help, but I don't want to answer the same question twice. :)
