### ISSUE TITLE
How to get the TGR dataset?

### ISSUE THREAD

**Issue by KevinHooah** [BrandonHanx/CompFashion#7]
Hi, may I ask if there is any generated TGR dataset for downloading? Or is there any kind of tutorial to generate the TGR dataset? Thank you very much!

**Comment by BrandonHanx** [comment]
Hi Thanks for your interest.

Please give me an email address then I will share the data with you :)

**Comment by KevinHooah** [comment]
Hi, thank you for your reply.

Could you share the dataset to `work.kevinhu [AT] gmail.com` ? Thanks!

**Comment by haokunwen** [comment]
May I ask if the TGR dataset is still available? If so, could you please share the dataset with me at whkicd[AT]gmail.com?

Thank you very much!
